version: '3.8'

services:
  learnmcp-xapi:
    build: .
    environment:
      - LRS_ENDPOINT=${LRS_ENDPOINT}
      - LRS_KEY=${LRS_KEY}
      - LRS_SECRET=${LRS_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-RS256}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-30}
      - MAX_BODY_SIZE=${MAX_BODY_SIZE:-16384}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./schemas:/app/schemas:ro
    restart: unless-stopped
    stdin_open: true
    tty: true