version: '3.8'

services:
  learnmcp-xapi:
    build: .
    environment:
      # Core Configuration
      - ENV=${ENV:-development}
      - ACTOR_UUID=${ACTOR_UUID}
      - LRS_PLUGIN=${LRS_PLUGIN:-lrsql}
      - CONFIG_PATH=${CONFIG_PATH:-./config}
      
      # Optional Configuration
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-30}
      - MAX_BODY_SIZE=${MAX_BODY_SIZE:-16384}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # LRS SQL Plugin Configuration (when LRS_PLUGIN=lrsql)
      - LRSQL_ENDPOINT=${LRSQL_ENDPOINT}
      - LRSQL_KEY=${LRSQL_KEY}
      - LRSQL_SECRET=${LRSQL_SECRET}
      
      # Ralph LRS Plugin Configuration (when LRS_PLUGIN=ralph)
      - RALPH_ENDPOINT=${RALPH_ENDPOINT}
      - RALPH_USERNAME=${RALPH_USERNAME}
      - RALPH_PASSWORD=${RALPH_PASSWORD}
      - RALPH_OIDC_TOKEN_URL=${RALPH_OIDC_TOKEN_URL}
      - RALPH_OIDC_CLIENT_ID=${RALPH_OIDC_CLIENT_ID}
      - RALPH_OIDC_CLIENT_SECRET=${RALPH_OIDC_CLIENT_SECRET}
      
      # Legacy Configuration (backward compatibility)
      - LRS_ENDPOINT=${LRS_ENDPOINT}
      - LRS_KEY=${LRS_KEY}
      - LRS_SECRET=${LRS_SECRET}
    volumes:
      - ./schemas:/app/schemas:ro
      - ./config:/app/config:ro
    restart: unless-stopped
    stdin_open: true
    tty: true

  # Example LRS SQL service for development
  lrsql:
    image: yetanalytics/lrsql:latest
    ports:
      - "8080:8080"
    environment:
      - LRSQL_DB_HOST=lrsql-db
      - LRSQL_DB_NAME=lrsql
      - LRSQL_DB_USER=lrsql
      - LRSQL_DB_PASSWORD=lrsql_password
    depends_on:
      - lrsql-db
    profiles:
      - lrsql-dev

  lrsql-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=lrsql
      - POSTGRES_USER=lrsql
      - POSTGRES_PASSWORD=lrsql_password
    volumes:
      - lrsql_data:/var/lib/postgresql/data
    profiles:
      - lrsql-dev

  # Example Ralph LRS service for development
  ralph:
    image: fundocker/ralph:latest
    ports:
      - "8100:8100"
    environment:
      - RALPH_BACKENDS__DATA__LRS__ES__HOSTS=http://ralph-es:9200
      - RALPH_BACKENDS__DATA__LRS__CLICKHOUSE__HOST=ralph-clickhouse
      - RALPH_BACKENDS__AUTH__BACKEND=basic
    depends_on:
      - ralph-es
      - ralph-clickhouse
    profiles:
      - ralph-dev

  ralph-es:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ralph_es_data:/usr/share/elasticsearch/data
    profiles:
      - ralph-dev

  ralph-clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ralph_ch_data:/var/lib/clickhouse
    profiles:
      - ralph-dev

volumes:
  lrsql_data:
  ralph_es_data:
  ralph_ch_data: